/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx,css,scss}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx,css,scss}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-100": "var(--primary-100)",
        "primary-200": "var(--primary-200)",
        "primary-300": "var(--primary-300)",
        "primary-400": "var(--primary-400)",
        "primary-500": "var(--primary-500)",
        "secondary-100": "var(--secondary-100)",
        "secondary-200": "var(--secondary-200)",
        "secondary-300": "var(--secondary-300)",
        "secondary-400": "var(--secondary-400)",
        "secondary-500": "var(--secondary-500)",
        "grey-50": "var(--grey-50)",
        "grey-100": "var(--grey-100)",
        "grey-200": "var(--grey-200)",
        "grey-300": "var(--grey-300)",
        "grey-400": "var(--grey-400)",
        "grey-500": "var(--grey-500)",
        "grey-600": "var(--grey-600)",
        "grey-700": "var(--grey-700)",
        "grey-800": "var(--grey-800)",
        "grey-900": "var(--grey-900)",
        "blue-50": "var(--blue-50)",
        "blue-250": "var(--blue-250)",
        "blue-400": "var(--blue-400)",
        "blue-500": "var(--blue-500)",
        "loss-100": "var(--loss-100)",
        "grey-unknown": "var(--grey-unknown)",
        "profit-100": "var(--profit-100)",
        "bg-base": "var(--bg-base)",
        "bg-disable": "var(--bg-disable)",
        "bg-overlay": "var(--bg-overlay)",
        "bg-sheet": "var(--bg-sheet)",
        "neutral-50": "var(--neutral-50)",
        "neutral-100": "var(--neutral-100)",
        "neutral-200": "var(--neutral-200)",
        "neutral-300": "var(--neutral-300)",
        "neutral-400": "var(--neutral-400)",
        "text-disable": "var(--text-disable)",
        "text-50": "var(--text-50)",
        "text-100": "var(--text-100)",
        "text-300": "var(--text-300)",
        "text-500": "var(--text-500)",
        "divider-100": "var(--divider-100)",
        "line-100": "var(--line-100)",
        "success-50": "var(--success-50)",
        "success-100": "var(--success-100)",
        "success-300": "var(--success-300)",
        "success-400": "var(--success-400)",
        "success-500": "var(--success-500)",
        "error-50": "var(--error-50)",
        "error-100": "var(--error-100)",
        "error-300": "var(--error-300)",
        "error-400": "var(--error-400)",
        "error-500": "var(--error-500)",
        "notice-100": "var(--notice-100)",
        "notice-500": "var(--notice-500)",
        "warning-100": "var(--warning-100)",
        "warning-500": "var(--warning-500)",
        "icon-primary": "var(--icon-primary)",
        "icon-secondary": "var(--icon-secondary)",
        "icon-tertiary": "var(--icon-tertiary)",
        "icon-disable": "var(--icon-disable)",
        turq: "var(--turq)",
        teal: "var(--teal)",
        honey: "var(--honey)",
        raspberry: "var(--raspberry)",
        "dark-blue": "var(--dark-blue)",
        purple: "var(--purple)",
        pink: "var(--pink)",
        red: "var(--red)",
        orange: "var(--orange)",
        white: "var(--white)",
        black: "var(--black)",
        sapphire: "var(--sapphire)",
        profit: "var(--profit)",
      },
      fontWeight: {
        bold: "700",
        semibold: "600",
        normal: "400",
      },
      fontSize: {
        xxsmall: ["9px", { lineHeight: "12px" }],
        xsmall: ["10px", { lineHeight: "14px" }],
        small: ["12px", { lineHeight: "16px" }],
        medium: ["14px", { lineHeight: "20px" }],
        large: ["16px", { lineHeight: "24px" }],
        xlarge: ["18px", { lineHeight: "28px" }],
        xxlarge: ["20px", { lineHeight: "28px" }],
        xxxlarge: ["22px", { lineHeight: "30px" }],
        "d-xsmall": ["24px", { lineHeight: "32px" }],
        "d-small": ["30px", { lineHeight: "36px" }],
        "d-medium": ["36px", { lineHeight: "44px" }],
        "d-large": ["48px", { lineHeight: "56px" }],
        "d-xlarge": ["72px", { lineHeight: "80px" }],
      },
      screens: {
        sm: "770px",
        md: "880px",
        lg: "1100px",
        xl: "1200px",
      },
    },
  },
  plugins: [],
};
