export const skills = [
  {
    title: "Development",
    value: [
      {
        img: "logo_reactjs.png",
        label: "ReactJS",
        slug: "react-js",
        url: "https://reactjs.org",
        firstColor: "#F0326E",
        secondColor: "#802C6E",
      },
      {
        img: "logo_nextjs.png",
        label: "NextJS",
        slug: "next-js",
        url: "https://nextjs.org",
        firstColor: "#CBF2D6",
        secondColor: "#865AC4",
      },
      {
        img: "logo_vuejs.png",
        label: "VueJS",
        slug: "vue-js",
        url: "https://vuejs.org",
        firstColor: "#FDF6F0",
        secondColor: "#FBBC58",
      },
      {
        img: "logo_nuxtjs.png",
        label: "NuxtJS",
        slug: "nuxt-js",
        url: "https://nuxtjs.org",
        firstColor: "#EED5D1",
        secondColor: "#D0114D",
      },
      {
        img: "logo_nodejs.png",
        label: "NodeJS",
        slug: "node-js",
        url: "https://nodejs.org/en/",
        firstColor: "#FDC2B1",
        secondColor: "#D186A0",
      },
      {
        img: "logo_swiftui.png",
        label: "SwiftUI",
        slug: "swiftui",
        url: "https://developer.apple.com/xcode/swiftui/",
        firstColor: "#EECECE",
        secondColor: "#CF5991",
      },
      {
        img: "logo_html.png",
        label: "Html",
        slug: "html",
        url: "https://developer.mozilla.org/id/docs/Web/Guide/HTML/HTML5",
        firstColor: "#043353",
        secondColor: "#18A4E0",
      },
      {
        img: "logo_css.png",
        label: "Css",
        slug: "css",
        url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
        firstColor: "#FDD3E4",
        secondColor: "#C63968",
      },
      {
        img: "logo_postgresql.png",
        label: "PostgreSQL",
        slug: "postgresql",
        url: "https://vuejs.org",
        firstColor: "#B4E55C",
        secondColor: "#275A53",
      },
      {
        img: "logo_graphql.png",
        label: "GraphQL",
        slug: "graphql",
        url: "https://www.postgresql.org/",
        firstColor: "#7ED19A",
        secondColor: "#5198B7",
      },
      {
        img: "logo_expressjs.png",
        label: "ExpressJS",
        slug: "express-js",
        url: "https://expressjs.com/",
        firstColor: "#7ED19A",
        secondColor: "#5198B7",
      },
      {
        img: "logo_mysql.png",
        label: "MySQL",
        slug: "mysql",
        url: "https://www.mysql.com/",
        firstColor: "#F0EFEA",
        secondColor: "#D5C4B4",
      },
      {
        img: "logo_prisma.png",
        label: "Prisma",
        slug: "prisma",
        url: "https://www.prisma.io/",
        firstColor: "#FAF8ED",
        secondColor: "#B9A6E0",
      },
    ],
  },
  {
    title: "Design Tools",
    value: [
      {
        img: "logo_figma.png",
        label: "Figma",
        slug: "figma",
        url: "http://figma.com/",
        firstColor: "#F5C6AB",
        secondColor: "#B40D1A",
      },
      {
        img: "logo_marvel.png",
        label: "Marvel",
        slug: "marvel",
        url: "https://marvelapp.com/",
        firstColor: "#7ED19A",
        secondColor: "#5198B7",
      },
      {
        img: "logo_sketch.png",
        label: "Sketch",
        slug: "marvel",
        url: "https://marvelapp.com/",
        firstColor: "#7ED19A",
        secondColor: "#5198B7",
      },
      {
        img: "logo_xd.png",
        label: "Adobe XD",
        slug: "xd",
        url: "https://marvelapp.com/",
        firstColor: "#7ED19A",
        secondColor: "#5198B7",
      },
      {
        img: "logo_photoshop.png",
        label: "Photoshop",
        slug: "marvel",
        url: "https://marvelapp.com/",
        firstColor: "#7ED19A",
        secondColor: "#5198B7",
      },
      {
        img: "logo_lightroom.png",
        label: "Lightroom",
        slug: "lightroom",
        url: "https://marvelapp.com/",
        firstColor: "#7ED19A",
        secondColor: "#5198B7",
      },
      {
        img: "logo_premiere.png",
        label: "Premiere",
        slug: "premiere",
        url: "https://marvelapp.com/",
        firstColor: "#7ED19A",
        secondColor: "#5198B7",
      },
      {
        img: "logo_aftereffect.png",
        label: "Adobe AE",
        slug: "ae",
        url: "https://marvelapp.com/",
        firstColor: "#7ED19A",
        secondColor: "#5198B7",
      },
    ],
  },
  {
    title: "Product Tools",
    value: [
      {
        img: "logo_notion.png",
        label: "Notion",
        slug: "marvel",
        url: "https://marvelapp.com/",
        firstColor: "#7ED19A",
        secondColor: "#5198B7",
      },
      {
        img: "logo_office.png",
        label: "Office",
        slug: "marvel",
        url: "https://marvelapp.com/",
        firstColor: "#7ED19A",
        secondColor: "#5198B7",
      },
      {
        img: "logo_asana.png",
        label: "Asana",
        slug: "marvel",
        url: "https://marvelapp.com/",
        firstColor: "#7ED19A",
        secondColor: "#5198B7",
      },
    ],
  },
];
