export interface IColor {
  "primary-100": string;
  "primary-200": string;
  "primary-300": string;
  "primary-400": string;
  "primary-500": string;
  "secondary-100": string;
  "secondary-200": string;
  "secondary-300": string;
  "secondary-400": string;
  "secondary-500": string;
  "grey-50": string;
  "grey-100": string;
  "grey-200": string;
  "grey-300": string;
  "grey-400": string;
  "grey-500": string;
  "grey-600": string;
  "grey-700": string;
  "grey-800": string;
  "grey-900": string;
  "blue-50": string;
  "blue-250": string;
  "blue-400": string;
  "blue-500": string;
  "loss-100": string;
  "grey-unknown": string;
  "profit-100": string;
  "bg-base": string;
  "bg-disable": string;
  "bg-overlay": string;
  "bg-sheet": string;
  "neutral-50": string;
  "neutral-100": string;
  "neutral-200": string;
  "neutral-300": string;
  "neutral-400": string;
  "text-disable": string;
  "text-50": string;
  "text-100": string;
  "text-300": string;
  "text-500": string;
  "divider-100": string;
  "line-100": string;
  "success-100": string;
  "success-500": string;
  "error-100": string;
  "error-500": string;
  "notice-100": string;
  "notice-500": string;
  "warning-100": string;
  "warning-500": string;
  "icon-primary": string;
  "icon-secondary": string;
  "icon-tertiary": string;
  "icon-disable": string;
  turq: string;
  teal: string;
  honey: string;
  raspberry: string;
  "dark-blue": string;
  purple: string;
  pink: string;
  red: string;
  orange: string;
  white: string;
  black: string;
  sapphire: string;
  profit: string;
}

export type ColorType =
  | "primary-100"
  | "primary-200"
  | "primary-300"
  | "primary-400"
  | "primary-500"
  | "secondary-100"
  | "secondary-200"
  | "secondary-300"
  | "secondary-400"
  | "secondary-500"
  | "grey-50"
  | "grey-100"
  | "grey-200"
  | "grey-300"
  | "grey-400"
  | "grey-500"
  | "grey-600"
  | "grey-700"
  | "grey-800"
  | "grey-900"
  | "blue-50"
  | "blue-250"
  | "blue-400"
  | "blue-500"
  | "loss-100"
  | "grey-unknown"
  | "profit-100"
  | "bg-base"
  | "bg-disable"
  | "bg-overlay"
  | "bg-sheet"
  | "neutral-50"
  | "neutral-100"
  | "neutral-200"
  | "neutral-300"
  | "neutral-400"
  | "text-disable"
  | "text-50"
  | "text-100"
  | "text-300"
  | "text-500"
  | "divider-100"
  | "line-100"
  | "success-50"
  | "success-100"
  | "success-300"
  | "success-400"
  | "success-500"
  | "error-50"
  | "error-100"
  | "error-300"
  | "error-400"
  | "error-500"
  | "notice-100"
  | "notice-500"
  | "warning-100"
  | "warning-500"
  | "icon-primary"
  | "icon-secondary"
  | "icon-tertiary"
  | "icon-disable"
  | "turq"
  | "teal"
  | "honey"
  | "raspberry"
  | "dark-blue"
  | "purple"
  | "pink"
  | "red"
  | "orange"
  | "white"
  | "black"
  | "sapphire"
  | "profit";
