import classNames from "classnames";
import { Inter } from "next/font/google";

import { openSans } from "@/components/Text/Text.component";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={classNames(inter.variable, openSans.variable)}>
      <body>{children}</body>
    </html>
  );
}
